export enum MetaDataType {
  COURSE = 'course',
  COURSE_SPECIALIZATION = 'course_specialization',
  BLOG = 'blog',
  EVENT = 'event',
  WEBINAR = 'webinar',
  GALLERY = 'gallery',
  UNIVERSITY = 'university',
  PAGE_CONTENT = 'page-content',
  MEDIA = 'media',
  FAQ = 'FAQ',
  FAQTOPIC = 'faq-topic',
  GLOBAL_PARTNER = 'global-partner',
  GENRAL = 'genral',
  CONTACTS = 'contacts',
}
